name: Release
on: [push]
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: pull, build and execute on typo server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
            #sudo service palantir-nightly stop
            cd /home/pi/Palantir-Rebirth
            sudo git pull
            sudo dotnet build
            #sudo service palantir-nightly start
            tmux send-keys -t palantir-nightly.0 "C-c" Enter
            tmux send-keys -t palantir-nightly.0 "cd /home/pi/Palantir-Rebirth/" Enter
            tmux send-keys -t palantir-nightly.0 "sudo dotnet bin/Debug/net7.0/Palantir-Rebirth.dll /home/pi/Palantir-Rebirth/config.json" Enter